### ISSUE TITLE
Minor Screen Issue

### ISSUE THREAD

**Issue by dfafard** [frequent/multiview#1]
Hi, love multiview.. hope to see it fully fleshed out.

When trying, I turned my iPad to Portait and I get a large white swatch running on left side, turning back to Landscape produces more white space. I can provide screen shot if needed.

Thanks for al your work!
Dave

**Comment by frequent** [comment]
Fixed this yesterday. Will be working after next commit.

**Comment by frequent** [comment]
Should work now. I'm closing. If it doesn't please reopen.
