### ISSUE TITLE
Dialog remains after closing.

### ISSUE THREAD

**Issue by 29alabs** [frequent/multiview#10]
I'm experimenting an issue with dialogs.

Declaring, opening and working on them is fine but the moment I close them a phantom dialog (div) remains that blocks buttons and links.

My multiview configuration is very simple, just a menu panel and a main panel (and using scrollview for scrolling lists) and this issue is being baffling me for some time, so, I'm wondering if dialogs are not supported, declaring them is different from vanilla jquery mobile or  is it an issue within multiview that could be resolved in the future.

Thanks for your help and excellent work with multiview, I love it.

**Comment by frequent** [comment]
Ok. I can reproduce this. Must be an issue somewhere. Let me see if I can find it.

**Comment by frequent** [comment]
Fixed. You need to update both the multiview.js AND customized jquery-mobile.1.1.0.multiview.js.

If you want the "nitty-gritty", there were two mistakes: 
1. JQM on pagehide runs a function to remove activeClass. I added an IF to also remove the active class from the wrapper page. I had a _return_ in this IF-clause which stopped the function before clearing active class from the dialog. Removed _return_. Now it works.
2. Second mistake was I did not check for dialogs when modifying and cleaning up the urlHistory. I needed to exclude dialogs from my panel-navigation edge case (= last backwards transition on a panel) and block dialog transitions from my internal panel-transition counter. 

Here is a quick sample page: [dialog.html](http://www.stokkers.mobi/jqm/multiview/demo_dialog.html). 

The first dialog opens dummy.html page, the 2nd one is a custom select opening as a fullscreen page. Both are working ok now here = the input below is clickable AND you will not get dialogs messing up the urlHistory and browser back button. I'm closing this. If it's not working for you, please re-open.

**Comment by 29alabs** [comment]
Incredible.

I figured it was more than a class causing trouble because I tried to get rid of the remaining DIV in ghetto ways (using top or webkit transforms) but dialogs wouldn't open again.

This works like a charm and no modifications to my code needed, thank you so much.
