### ISSUE TITLE
Sizing popovers

### ISSUE THREAD

**Issue by kevkha** [frequent/multiview#13]
Hi frequent,

The doc says "Popovers can be any size...".  Where and how to achieve this? I would like to have my popovers in different sizes. Thanks.

**Comment by frequent** [comment]
I made a small commit bundling all size&position CSS in a single class, so they are easier to change. In the example, the popover has a class of **popover1**, with CSS like so:

```
  .popover1 { margin-top: 3.25em; right: 5em;  height:25em; width: 15em; top: 0; display: none;}
```

Just overwrite those properties or add you own class **my_popopver_css** to your popover panel. 

Please note the position currently as to be set using _margin-top_ and _right_. I haven't tried the other properties, but this works.

**Comment by kevkha** [comment]
It works like a charm. Thanks very much for your prompted response and speedy turnaround.
