### ISSUE TITLE
Custom jQuery scripts not load

### ISSUE THREAD

**Issue by kevkha** [frequent/multiview#16]
I'm using Template Toolkit for my HTML pages. For instance I have these templates
(note: I remove the tailing > tags to show on this comment)

header.tmpl

<!DOCTYPE html
 <header
     < all css and jquery, jqm and customer jquery scripts goes here>
  </header
<body

main.tmpl

wrapper page
  menu panel
    main panel

ftooter.tmpl

  </ body
</ html

By default main.tmpl loads the header.tmpl and footer.tmpl and all is fine. JQM theme and everything else looks just fine. I inspected the HTML source via a browser and there is no missing components.

However, on the search menu I have search index link say (href="?cmd=browse&s=A") which loads search.tmpl and this template has the same multiview layout requirement as main.tmpl (wrapper, menu and main panel). The search results returns successfully but I cannot use the custom jquery script here until I physically hit the browser refresh button.

The custom jquery script simply allows the user to Check All and Clear All the items from a form in listview with checkbox. The script works fine when refresh the page on demand. Any idea how to achieve this with JQM MultiView? Thanks a lot in advance.

**Comment by frequent** [comment]
Sounds more like a problem delegating events with _$('document').delegate_ or _$(document).on_ or _live_. 

The plugin only does formatting and panel navigation. In panel navigation, it intercepts JQM changepage, changes 

```
 data.toPage
 data.options.fromPage
 data.options.pageContain
```

in case of panel transition and then lets the original event pass through. So it's actually _only_ normal JQM. 

If you are missing your bindings, try setting some dummys as above with _alerts("clicked")_ and check if they trigger. 

Closing this again. Please re-open if you can pinpoint it to something not working in the plugin.
