### ISSUE TITLE
Navigation between panels

### ISSUE THREAD

**Issue by balajisn** [frequent/multiview#17]
Hi Frequent,

For navigation between the panels, I used $.mobile.changePage and the syntax as mentioned like:

$.mobile.changePage('#page', {pageContainer: $('div:jqmData(id="your-panel-name")') });

Here, as per the documentation, it says data-panel="your-panel-name".  Where should this data-panel="your-panel-name" be provided??  Because the data-panel takes Menu|Mid|Main|Popover values.

Should this data-panel="your-panel-name" be provided on the anchor tag like this:

&lt;a href="javascript:void(0)" data-panel="menu1" onclick="navTo('menu1');">Menu 1&lt;/a>

where navTo is a custom function as below:

function navTo(pageId) {
    var id = '\'div:jqmData(id="menu1")\'';
    if (pageId == 'menu2') {
        id = '\'div:jqmData(id="menu2")\'';
    } else if (pageId == 'menu3') {
        id = '\'div:jqmData(id="menu3")\'';
    } else if (pageId == 'menu4') {
        id = '\'div:jqmData(id="menu4")\'';
    }
    $.mobile.changePage('#' + pageId, {pageContainer: $(id)});
}

After doing this, the navigation was unsuccessfull.

Here is my sample code (have just pasted the body part of the html):

&lt;body>  
    &lt;!-- wrapper -->
    &lt;div data-role="page" id="container" data-wrapper="true">  
        &lt;!--- panel --->
        &lt;div data-role="panel" data-id="menu" data-panel="menu">
            &lt;div data-role="page" id="menu_first" data-show="first">
                &lt;div data-role="header" data-position="inline" data-theme="b">
                    &lt;a href="javascript:void(0)" data-icon="star" iconpos="right">Sync&lt;/a>
                    &lt;h1>Menu&lt;/h1>  
                    &lt;a href="javascript:void(0)" data-iconpos="notext" data-icon="gear" iconpos="right">Settings&lt;/a>
                &lt;/div>
                &lt;div data-role="content">
                    &lt;ul data-role="listview" data-inset="true">
                        &lt;li>&lt;a href="javascript:void(0)" data-panel="menu1" onclick="navTo('menu1');">Menu 1&lt;/a>&lt;/li>
                        &lt;li>&lt;a href="javascript:void(0)" data-panel="menu2" onclick="navTo('menu2');">Menu 2&lt;/a>&lt;/li>
                        &lt;li>&lt;a href="javascript:void(0)" data-panel="menu3" onclick="navTo('menu3');">Menu 3&lt;/a>&lt;/li>
                        &lt;li>&lt;a href="javascript:void(0)" data-panel="menu4" onclick="navTo('menu4');">Menu 4&lt;/a>&lt;/li>
                    &lt;/ul>
                &lt;/div>&lt;!-- /content -->
            &lt;/div>
        &lt;/div>
        &lt;!--- panel --->
        &lt;div data-role="panel" data-id="main" id="main" data-panel="main">
            &lt;div data-role="page" id="menu1" data-show="first">
                &lt;div data-role="header" data-position="inline" data-theme="b">
                    &lt;a href="javascript:void(0)" data-icon="star" iconpos="right">Done&lt;/a>
                    &lt;h1>Contents&lt;/h1>  
                    &lt;a href="javascript:void(0)" data-iconpos="notext" data-icon="gear" iconpos="right">New&lt;/a>
                &lt;/div>
                &lt;div data-role="content">
                    Menu 1 Contents
                &lt;/div>
            &lt;/div>
            &lt;div data-role="page" id="menu2">
                &lt;div data-role="header" data-position="inline" data-theme="b">
                    &lt;a href="javascript:void(0)" data-icon="star" iconpos="right">Done&lt;/a>
                    &lt;h1>Contents&lt;/h1>  
                    &lt;a href="javascript:void(0)" data-iconpos="notext" data-icon="gear" iconpos="right">New&lt;/a>
                &lt;/div>
                &lt;div data-role="content">
                    Menu 2 Contents
                &lt;/div>
            &lt;/div>
            &lt;div data-role="page" id="menu3">
                &lt;div data-role="header" data-position="inline" data-theme="b">
                    &lt;a href="javascript:void(0)" data-icon="star" iconpos="right">Done&lt;/a>
                    &lt;h1>Contents&lt;/h1>  
                    &lt;a href="javascript:void(0)" data-iconpos="notext" data-icon="gear" iconpos="right">New&lt;/a>
                &lt;/div>
                &lt;div data-role="content">
                    Menu 3 Contents
                &lt;/div>
            &lt;/div>
            &lt;div data-role="page" id="menu4">
                &lt;div data-role="header" data-position="inline" data-theme="b">
                    &lt;a href="javascript:void(0)" data-icon="star" iconpos="right">Done&lt;/a>
                    &lt;h1>Contents&lt;/h1>  
                    &lt;a href="javascript:void(0)" data-iconpos="notext" data-icon="gear" iconpos="right">New&lt;/a>
                &lt;/div>
                &lt;div data-role="content">
                    Menu 4 Contents
                &lt;/div>
            &lt;/div>
        &lt;/div>
    &lt;/div>  
&lt;/body>

Could you please advise me on this?

Thanks,
Balaji.S.N

**Comment by frequent** [comment]
_your_panel_name_ is the **data-id** you give to a panel. So a panel will be:

```
<div data-role="panel" data-panel="menu|main..." data-id="your_panel_name">

</div>
```

So, if your menu panel is named "foobar" = data-id="foobar", on links you do this:

```
<a href="somePage.html" data-panel="foobar">button</a>
```

And changePage:

```
$.mobile.changePage( "somePage.html", {pageContainer: $('div:jqmData(id="foobar")') }
```

I admit, it's a bit confusing, but I had to switch from using data-target, because JQM will use it for JQM 1.2/3 fetchlink. So I switchted to data-panel, which already was in use on the panel itself. Maybe I should eventually change to 

```
 <div data-role="panel" data-TYPE="main|menu" data-id="foobar"></div>
```

Anyway, the _data-id_ is necessary if you have more than one multivew page in your app (I guess as your example). Because if JQM pulls in the 2nd multiview page and both have menu/main, the navigation would break if you would simply say "changePage on main panel", because there would be two main panels. Therefore data-id.

PS: In your example

```
   <div data-role="panel" data-id="main" id="main" data-panel="main">
```

the main panel should not have an _id_. Haven't tried if this works, but I'd rather not use it (same reason JQM recommended classes to not confuse navigation.
