### ISSUE TITLE
Error while loading of the Jquery.mobile.1.1.0.multiview.js file

### ISSUE THREAD

**Issue by hetang** [frequent/multiview#22]
Hi,
   I have followed your steps and try to implement the multiview plugin but at the start of the page load I am getting error at line number 8546 "this.element is undefined". Please guide me to resolve this error.

**Comment by frequent** [comment]
Please provide some code.

**Comment by hetang** [comment]
I solved the issue I wrongly typed the HTML structure. because of this it causing error. Thanks for the quick reply.

**Comment by frequent** [comment]
Good. You can use [this](http://www.stokkers.mobi/jqm/multiview/test/fix_triplePop.html) as a template. Just leave away what you don't need.

**Comment by hetang** [comment]
Sure. Thanks. Great work :)
