### ISSUE TITLE
Bottom bar keep flashing

### ISSUE THREAD

**Issue by sstraus** [frequent/multiview#25]
Hello, I'm testing tour amazing plugin but i have some strange issues with the bottom bar. It keeps flashing and disappearing.
I noticed this strange behaviour also on your demo page.

Btw I run it on an iPad 1st gen.

Regards.

**Comment by frequent** [comment]
Hi there,

I'm also running 1st gen Ipad. I have a big update with a lot of fixing coming up. I'm testing right now and toolbars behave nicely on iPad. Few days.

Regards,

Sven

**Comment by sstraus** [comment]
Thank you, I'm using your plugin with PhoneGap on Ipad 1,2,3 so I can let you know how it run once released.
Independently from your great work, I noticed that listviews are also really slow with just 100 items loaded in. IT but affects only Safari on the Ipad. Have you a solution for this too?

Regards,
Stefano

-----Messaggio originale-----
Da: Sven Franck [mailto:reply@reply.github.com] 
Inviato: lunedì 25 giugno 2012 09:14
A: Stefano Straus
Oggetto: Re: [multiview] Bottom bar keep flashing (#25)

Hi there,

I'm also running 1st gen Ipad. I have a big update with a lot of fixing coming up. I'm testing right now and toolbars behave nicely on iPad. Few days.

Regards,

Sven

> ---
> 
> From: sstraus reply@reply.github.com
> To: Sven Franck svenfranck@yahoo.com 
> Sent: Monday, June 25, 2012 7:48 AM
> Subject: [multiview] Bottom bar keep flashing (#25)
> 
> Hello, I'm testing tour amazing plugin but i have some strange issues with the bottom bar. It keeps flashing and disappearing.
> I noticed this strange behaviour also on your demo page.
> 
> Btw I run it on an iPad 1st gen.
> 
> Regards.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frequent/multiview/issues/25

---

**Comment by frequent** [comment]
Sounds good. Regarding listiviews see this [issue](https://github.com/jquery/jquery-mobile/issues/4340), which was solved by JQM yesterday and should be working in their next release/latest build.

**Comment by sstraus** [comment]
You are a Goldmine!! Thanks

-----Messaggio originale-----
Da: Sven Franck [mailto:reply@reply.github.com] 
Inviato: lunedì 25 giugno 2012 15:28
A: Stefano Straus
Oggetto: Re: [multiview] Bottom bar keep flashing (#25)

Sounds good. Regarding listiviews see this [issue](https://github.com/jquery/jquery-mobile/issues/4340), which was solved by JQM yesterday and should be working in their next release/latest build.

---

**Comment by sstraus** [comment]
Hi Sven, I fixed multiview with the patches taken from the issue #4340 and now is a bit better, but is not smooth and once scrolled will re-appear 2 second later. The tap now performs well.
I'll wait for your fixes, my knowledge of JQM core is very basic.

-----Messaggio originale-----
Da: Sven Franck [mailto:reply@reply.github.com] 
Inviato: lunedì 25 giugno 2012 15:28
A: Stefano Straus
Oggetto: Re: [multiview] Bottom bar keep flashing (#25)

Sounds good. Regarding listiviews see this [issue](https://github.com/jquery/jquery-mobile/issues/4340), which was solved by JQM yesterday and should be working in their next release/latest build.

---

**Comment by frequent** [comment]
@sstraus: can you check the bottom bar with the latest version? I CSS-ed forever to get it to work on iPad1... The content height should now be set to "at-least" screen height less global toolbars, so the footer should always stick to the end of the content section and not flash in/out when tapping the screen. At least on iPad 1 it's ok now.

**Comment by sstraus** [comment]
Hello, I just replaced JS files and now the only visible part is the bottom part. No split page or content at all.

**Comment by frequent** [comment]
Please try the fix I just commited. 

I'm working with this version right now and panels are visible. Although I have found some other glitches, namely "overthrow" not being added and panels missing some classes. I try to patch these up as I work on my project (using multiview) this weekend. 

Let me know if this fixes visibility. For the rest check back later.

**Comment by sstraus** [comment]
Nello Sven, 
have you found where my issue come from during your weekend development?

Regards,
S.

Il giorno 30/giu/2012, alle ore 12:27, "Sven Franck" reply@reply.github.com ha scritto:

**Comment by Golodhros** [comment]
Hi sstraus and frequent,

I had a similar problem with the footer and the header, they keep on flashing and changing positions whenever I clicked or tapped in an empty area of my UI. 

It results that every time a click in an empty area, the class "ui-fixed-hidden" is added to the header and footer. This class asigns position:absolute, so that you would only need to overwrite it with position: fixed. In my specific case was something like this:

#menu_first .ui-footer { position: fixed; }

I hope it is useful!
