### ISSUE TITLE
PopOver showing and Hiding in Javascript

### ISSUE THREAD

**Issue by hetang** [frequent/multiview#26]
Hey Hi,
        I am uses your multiview plugin for popover. Can you please guide me how can I show or hide popover in JavaScript. and Does your recent changes includes any fixes for popover?

**Comment by frequent** [comment]
@hetang 

Latest version is in. To show/hide I'm triggering a click on the button like so: 

```
 $('div:jqmData(wrapper="true")').find('.toggle_popover:jqmData(panel="'+popover_panel_to_show+'")').trigger('click');
```

Eventually you will be able to call showPanel() or HidePanels() function. Currently they are not callable however. Closing this, if you have question, please reopen.

**Comment by hetang** [comment]
@frequent I tried to do it But I am opening this popup on a click of a button this is not a link. I tried suggested approach but it is not working. Can you Please suggest when the showPanel() and hidePanel() is going to available on click of a button.
