### ISSUE TITLE
menu and min panel can't scroll 

### ISSUE THREAD

**Issue by mrjikey** [frequent/multiview#29]
i have set data-scrollmode="overthrow" to my demo file.... below link is with the old js file which is  able to scroll the menu n mid panel.

http://g2o.com.my/mobi

below this link which is using today new update .. on the js ... but it doesn't  able to scroll the menu and mid panel.
http://g2o.com.my/mobi2

**Comment by frequent** [comment]
mh. both panels page content needs class **overthrow**. Let me check, why it is not assigned.

**Comment by mrjikey** [comment]
hello ... how's everything going?

**Comment by frequent** [comment]
drowning.... need a few more days before I can look into multiview

**Comment by Golodhros** [comment]
Hi there!

I have the same problem here... 

Many thanks for your work!

**Comment by frequent** [comment]
Should be fixed. Can only test tonight on a mobile device.

[Sample page](http://www.franckreich.de/jqm/test.html)

[Commit](https://github.com/frequent/multiview/commit/207b3edabd7a9d3894fe6554bebb103de6e7b0c4)

Please reopen if this doesn't work or breaks something else (shouldn't)

**Comment by Golodhros** [comment]
It works! Many thanks!
