### ISSUE TITLE
Does anyone know if this works with PhotoSwipe?

### ISSUE THREAD

**Issue by NewMediaRoc** [frequent/multiview#3]
I have had trouble with a different splitview plugin (https://github.com/asyraf9/jquery-mobile/#readme) working with the PhotoSwipe plugin. So, before I go wasting another day trying to get it to work, I was wondering if anyone has used this for a split view with photoswipe gallery already.

**Comment by frequent** [comment]
Hey NewMediaRoc,

Photoswipe should work ok. I have redone portions of the plugin to upgrade to jqm 1.0.1., but I still need to commit my latest version. I will try to commit tonight. If I find a working example with Photoswipe, which I did before, I will send it to you, too. 

Regards,
Frequent

**Comment by NewMediaRoc** [comment]
Awesome! Thanks for the quick response! I'll definitely give it a try today and let you know how it turns out :o)

**Comment by frequent** [comment]
please wait for my commit today :-)

**Comment by frequent** [comment]
Closing this. Re-Open if you run into troubles.
