### ISSUE TITLE
Back buttons

### ISSUE THREAD

**Issue by s0kAr** [frequent/multiview#32]
Hi.

Is it possible to hide the text for the automatically inserted back buttons on the main panel header?

Greetings

**Comment by s0kAr** [comment]
Hi frequent,

actually I use the version 1.1.1. 
In the multiview.js there is an option backBtnOff. But when I set it to true, the Back-Buttons will still appear.

After some navigation clicks, the history seems to be damaged. 
In my project I have one Wrapper page with a menu panel and a data panel.

The best way I think is to "disable" the construction of these buttons or?

Greetings, s0kAr

**Comment by Golodhros** [comment]
That's true,

the error is that multiview is only checking whether backBtnOff is false, but not if it is true. You just need to comment the line
self.crumble(event, data, page );

that is around line #2461. That should be enough.

**Comment by s0kAr** [comment]
Thanks a lot!
Now everything is fine :-).

**Comment by frequent** [comment]
@s0kAr, @Golodhros 

I'm changing this option to are more understandable `useBackBtn=true|false`

The new version will do this:

```
var prevPageWrap = data.prevPage.jqmData("wrapper"),
     panelTransition = typeof prevPageWrap == "undefined" || prevPageWrap == true,
     pageBackBtn = page.closest('div:jqmData(wrapper="true")').jqmData("useBackBtn"),
     useBackBtn =  pageBackBtn || o.useBackBtn

if ( useBackBtn && !prevPageWrap ){
    self.crumble(event, data, page );
    }
```

So there will be NO back buttons if (1) you do a transition from JQM page > wrapper page ("undefined"), (2) wrapper > wrapper ("true"), (3) you specifiy it on the wrapper page or (4) in the options (with page setting overriding options). I also added a rule that if the back button would lead to an undefined page, it will not be shown (for example if you start on a deeplink).
