### ISSUE TITLE
Changing window width breaks layout ...

### ISSUE THREAD

**Issue by Lichterloh** [frequent/multiview#34]
Hi, I just experienced a bad behavior when I changed the width of a page.

You can test this with demo version. Here you can see a screenshot of the issue (tested it with Firefox and Safari).

http://cl.ly/1E0I2c451C3h3I0K3I2y

Any hints how to solve this?

Thanks in advance and thanks for your great framework! It is awesome!

best regards,

Fabian

**Comment by frequent** [comment]
Hey. I'm still busy with my current project. Multiview needs to wait until I'm done.

**Comment by Lichterloh** [comment]
Dear Sven, do you know when you will be available next time to check this issue? 

Best regards,

Fabian

**Comment by frequent** [comment]
Sorry... end of the month earliest. I'm working with it, so any bugs I'm finding I'm patching up on the way.

**Comment by Lichterloh** [comment]
Thanks a lot! Great work so far!

**Comment by frequent** [comment]
@Lichterloh 

Sorry for getting back late. Please have a look at #39, which is on the same topic. I have removed the `resize` event from my handler for changing between screen modes. `Resize` fires a lot when you modify the screen and every resize will trigger several functions in multiview to adapt the panels look, height and width. 

Adding resize is no problem but whenever you resize the window the browser will stall for 1-2+ sec until all functions have run (10 resize = do 10x setting splitview or popver & 10x calculating & setting wrapper/panel/page/content width).

Now if there was a `onresizeend` event... 

Hope this helps. You can just add the event if you feel like.
