### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by scruffian** [frequent/multiview#6]
Thanks for this plug in. It's a very fundamental feature that is missing in jQM.

I am having some problems making the links work at all. I have copied the code from the sample, which works fine, but if, for example, I want to add a link to the second page in main, this is how I am trying to do it:

&lt;a href="#main_second" data-panel="main"&gt;Link to page two&lt;/a&gt;

But this doesn't work.

I am using the version for jQM 1.1.0. Thanks for your help!

**Comment by frequent** [comment]
@scruffian: I'm still trying to set multiview up correctly with JQM 1.1. The current 1.1.RC2 version in my repo is not fully functional. Give me a few more days.

**Comment by scruffian** [comment]
Ok thank you! Good luck with it all, it's looking great...

**Comment by frequent** [comment]
@scruffian: 

latest version (JQM 1.1) is up. Navigation is now so-so (still needs fine tuning), but you can either use links

```
 <a href="some.html" data-panel="menu" data-role="button">go to some</a>
```

Or call changePage (be sure to include the panel-ID as pageContainer option!)

```
  $.mobile.changePage( "some.html", { pageContainer: $('div:jqmData(id="menu")') })
```

Closing this for now. I might run across some stuff I still need to test/fix. Here is a working Here is a template with [template page](http://www.stokkers.mobi/jqm/multiview/sample-nav.html):

**Comment by scruffian** [comment]
Thanks, it's working great now!
