### ISSUE TITLE
Menu footer

### ISSUE THREAD

**Issue by s0kAr** [frequent/multiview#7]
Hi.
Is it possible to create a menu-wide footer for a menu with 3 submenus/pages, so that you can switch the menu page by clicking on a link in the footer?
Something like:
<li><a href="#menuPage1" data-page="menu" data-transition="slideup">Menu 1</a></li>

**Comment by frequent** [comment]
not sure what you mean. If you want a footer that only spans the menu with 3 buttons? And all 3 buttons load pages into the menu? No problem. 

Just do a menu and main panel and put your footer on all three menu pages (inside(!) the panel. That should do. Please note the JQM 1.1 RC2 version is not done yet, I will need a couple of days to finish up (hopefully I won't run into anything tricky...)

**Comment by s0kAr** [comment]
Is it possible yet with JQM 1.1 RC2?

I will do something like that, but the menu page won't change:

```
   <div data-role="panel" data-id="menu" data-panel="menu" data-hash="crumbs">
        <div data-role="page" id="firstMenu" data-show="first">
            <div data-role="header" data-position="fixed" data-theme="a">                   
                <h1>MENU First</h1>
            </div>
            <div data-role="content" class="red">
                <p>Menu Lorem Ipsum</p>
                <ul data-role="listview">
                    <li>A</li>
                    <li>B</li>                      
                </ul>
            </div>  
    <div data-role="footer" data-position="fixed" data-id="ew-footer" class="nav-id">
      <div data-role="navbar" class="nav-id" data-grid="a">
        <ul>
          <li><a href="#firstMenu" data-panel="menu" data-inline="true" class="ui-btn-active" id="case" data-icon="custom">Menu 1</a></li>
          <li><a href="#secondMenu" data-panel="menu" data-inline="true" id="medication" data-icon="custom">Menu 2</a></li>
        </ul>
      </div>
    </div>
        </div>

        <div data-role="page" id="secondMenu">
            <div data-role="header" data-theme="a" >
                <h1>Second Page Menu</h1>
            </div>
            <div data-role="content" class="blue">
                <div>Lorem Ipsum</div>
            </div>
    <div data-role="footer" data-position="fixed" data-id="ew-footer" class="nav-id">
      <div data-role="navbar" class="nav-id" data-grid="a">
        <ul>
          <li><a href="#firstMenu" data-panel="menu" data-inline="true" class="ui-btn-active" id="case" data-icon="custom">Menu 1</a></li>
          <li><a href="#secondMenu" data-panel="menu" data-inline="true" id="medication" data-icon="custom">Menu 2</a></li>
        </ul>
      </div>
    </div>
        </div>              
   </div>
```

**Comment by frequent** [comment]
looks correct, but until I finish up the JQM 1.1 (RC2) panel navigation, it will not work :-) Please be patient

**Comment by s0kAr** [comment]
Ah ok :-). Thanks!

Actually I use the splitview plugin, but I will use multiview instead as soon as possible ;-). It's really nice!
What do you think, will the navigation work till monday? I have a presentationn ;-).

**Comment by frequent** [comment]
@s0kAr 

check out the JQM 1.1 folder. It has the latest version with so-so working navigation. I just got everything to work. Still needs a lot of fine-tuning, but you should be able to set up your footer for your presentation ;-)

Here is a sample link (and template) for the JQM 1.1 version. 

Here is a template with the [sample navigation](http://www.stokkers.mobi/jqm/multiview/sample-nav.html)

Just remove the global footer, middle panel and all popover panels,  add local footers on all 3 menu pages. Should be ok, unless footer buttons aren't working, which I have not tested so far. Good luck on Monday. Closing this issue.
