### ISSUE TITLE
Syntax error, unrecognized expression: 8000

### ISSUE THREAD

**Issue by eismi** [frequent/multiview#9]
Hi Sven,
i've a problem with your jqm multiview controller.
I'm using a webserver with the defined Port '8000' and if i click on a link in the menu panel, nothing happens. There is just a message fired in firebug ("Syntax error, unrecognized expression: 8000").
If i load the page on the local storage, it still works fine.

Do you have some ideas?

Thanks for your help
best regards
Michael

**Comment by frequent** [comment]
hm. what is your link-href in the link and your targetPanel? Also, please upgrade to the multiview.js and .css version I just commited. This does fix quite a few things. Maybe yours, too

**Comment by eismi** [comment]
the link href and target panel are the same like in you example "sample-nav.html"

the problem is that jquery-1.7.1.js is checking my URL with regular expressions when i click on a link and my URL looks like this "gs-sap-t81.test.net:8000/geb_html/hcm_test2/multiview/test-eismi.html"

the debugger jumps to line 4600 on jquery-1.7.1.js:
   PSEUDO: function( elem, match, i, array ) 

and the regex is on line 4232:
    PSEUDO: /:((?:[\w\u00c0-\uFFFF-]|\.)+)(?:((['"]?)((?:([^)]+)|[^()]*)+)\2))?/

**Comment by frequent** [comment]
is your link working in regular Jquery Mobile? 

Multiview is only changing Jquery Mobile changePage options ([here](http://jquerymobile.com/test/docs/api/methods.html)) - fromPage, pageContainer, toPage etc. so it should work with links Jquery Mobile "understands" 

Let me know if your page works in regular JQM. If yes, I will have to take a look.

**Comment by mykdspyk** [comment]
Hi Sven,

I'm actually quite new to using your plugin and I'm just wondering whether the issue above has been resolved? I'm actually getting the same error as above. I have used your latest plugin including the css files and just created a simple menus and pages but the navigation is not working due to the error described above.

Thanks.

**Comment by mykdspyk** [comment]
just to add.. I think the issue only occurs when running on a webserver. The page is working fine if run in local storage/file system.  

The Syntax error, unrecognized expression: <my_port_number> (in my case 8080) logs on Firebug each time I click on a menu. I am not sure if this might help but one thing I noticed is that each time I click refreshed, it navigates to the right page. To summarize:
1. Click on one of the menu on the menu panel/
2. Nothing will happen on the page and the error described above is shown on Firebug,
3. Clicking browser refresh button will actually make the work link and navigate to the right page.

**Comment by frequent** [comment]
@mykdspyk - issue hasn't been resolved, as I did not get an answer back from @eismi.

I'm pretty sure I know what the problem might be:
Either I still have a dummy link like $('#'+data.toPage) somewhere, or it will be my handling of the history, where I'm forced to check for data-url to construct back and forward links (as id is not always provided). 

So questions:
- what are your links looking like?
- if the linked to page is already in the DOM, what it it's data-url assigned by JQM to the div.data-role="page"?

Actually the navigation can only break in a few spots, so I will commit another multiview.js version with consoles. If you use this version and check Firebug it should tell you (and me) where it breaks. 

I will post again once the new commit is online. Should be today.

**Comment by mykdspyk** [comment]
@frequent - links are just a simple ones

from the menu panel:

 href="#page1" data-target="main">Page-1 Main
 href="#page2" data-target="main">Page-2 Main
href="#page3" data-target="main">Page-3 Main

and yes the linked page is already on the DOM under the main panel, the data-url assigned by JQM is just the page name it self, i.e data-url="page1", here's the whole generated div for the page 1:

div id="page1" class="ui-page-active ui-page ui-body-c" data-show="first" data-role="page" data-url="page1" tabindex="0" data-internal-page="true" style="padding-top: 43px; min-height: 374px; margin-left: 480px; width: 1440px;"

**Comment by frequent** [comment]
hm. Why are you using **data-target**? Is it still in the instructions somewhere? I had it in the plugin in earlier versions and needed to replace it with **data-panel** because JQM is using data-target for the fetchlink feature in JQM 1.2.

Can you try with **data-panel="your_panel_name"** and let me know if it works?

Also be sure, that you put the panel-type here (main/menu/popover...). This must be the data-id attribute, because if you have more than one multiview page, you have more than one main/menu... and then the plugin does not where to load a page

**Comment by mykdspyk** [comment]
ooppss. forgot to change it as I am trying some things out, I was actually using data-panel originally and gives the same problem. 

panel-type is also correct as I based in on your "sample-nav.html".

**Comment by mykdspyk** [comment]
as I've said previously, the page works fine if running the file standalone/locally as html page. The problem occurs when I run it on a webserver.

**Comment by frequent** [comment]
ok. can you replace the current multiview, with this one:

   [multiview with consoles](http://www.stokkers.mobi/jqm/multiview/test/jquery.mobile-1.1.0.multiview_con.js)

Please do the "click on link in menu to load page in main", that causes the error, copy the console and send it to me @ svenfranck@yahoo.com.

**Comment by frequent** [comment]
@mykdspyk - was your last post in reply to my latest comment?

**Comment by mykdspyk** [comment]
@frequent - no, that was meant for my last comment. :-) will try it with the one you post.

**Comment by frequent** [comment]
please try with the latest commit

**Comment by mykdspyk** [comment]
@frequent  - i have just tested your latest commit but nothing is rendering on the browser. tried you sample pages as well and it is also not rendering. Am i missing something? can't see any error being thrown on Firebug and when I check the DOM, the page is there with both the main and menu panel pages active.

**Comment by frequent** [comment]
@mykdspyk - confirmed. I'm also blank. Must be my activePageClass Handler. Give me a few minutes.

**Comment by frequent** [comment]
@mykdspyk - I have updated to the latest version of multiview, which fixed quite a few bugs in the navigation. If you want to give it a try and it still doesn't work with the latest version, please re-open.
